
include:
  - apigw/docker-compose.yaml

services:
  backend:
    container_name: backend
    build: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - kong-net

networks:
  kong-net:
    external: true
