volumes:
  kong_db: {}

networks:
  kong-net:
    driver: bridge

services:
  kong:
    image: kong:3.9.1-ubuntu
    container_name: kong
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong_dbless/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_LISTEN: 0.0.0.0:8000     # http://0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001

      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002,0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL:  http://localhost:8002     # external URL shown in links
      KONG_ADMIN_GUI_PATH: /
    volumes:
      - ./kong.yaml:/kong_dbless/kong.yaml
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"   # proxy (HTTP)
      - "8443:8443"   # proxy (HTTPS)
      - "8001:8001"   # admin API (HTTP)
      - "8444:8444"   # admin API (HTTPS)
      - "8002:8002"   # GUI HTTP
      - "8445:8445"   # GUI HTTPS
