volumes:
  kong_db: {}

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:17.5
    container_name: kong-database
    restart: unless-stopped
    networks:
      - kong-net
    volumes:
      - /kong_db/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"     # optional – expose DB to host for debugging

  kong-migrations:
    image: kong:3.9.1-ubuntu
    command: kong migrations bootstrap
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: kong:3.9.1-ubuntu
    container_name: kong
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002,0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL:  http://localhost:8002     # external URL shown in links
      KONG_ADMIN_GUI_PATH: /
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"   # proxy (HTTP)
      - "8443:8443"   # proxy (HTTPS)
      - "8001:8001"   # admin API (HTTP)
      - "8444:8444"   # admin API (HTTPS)
      - "8002:8002"   # GUI HTTP
      - "8445:8445"   # GUI HTTPS
